package org.pqcfuzz.run;

import org.pqcfuzz.classify.Outcome;
import org.pqcfuzz.mutate.MutatedInput;
import org.pqcfuzz.mutate.Mutator;
import org.pqcfuzz.target.FuzzTarget;
import org.pqcfuzz.target.Targets;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import java.util.random.RandomGeneratorFactory;

/**
 * Per-input comparison of the two arms (design amendment A7).
 *
 * <p>For each of the five target pairs whose seed corpora are byte-identical between Bouncy Castle and
 * the JDK, this drives one mutation stream, built exactly as {@link CampaignRunner} builds it, through
 * both targets and records the pair of outcomes for every input. Equal aggregate counts, which the
 * campaign reports give, do not by themselves show that the two implementations decided every input the
 * same way; this does. The decapsulation pair is excluded because its JDK key pair is generated by the
 * JDK and the inputs match in length and mutation but not in bytes.
 *
 * <pre>
 * java -XX:-OmitStackTraceInFastThrow -cp pqc-fuzz.jar org.pqcfuzz.run.ArmDiff \
 *     [--seed=N] [--inputs=N] [--timeout-ms=N] [--out=DIR] [--label=TEXT]
 * </pre>
 *
 * Needs a JDK that ships the ML-KEM and ML-DSA providers (JDK 24 or later).
 */
public final class ArmDiff {

    private static final List<String[]> PAIRS = List.of(
            new String[] {"ml-kem-768-pubkey-parse", "jdk-ml-kem-768-pubkey-parse"},
            new String[] {"ml-kem-768-parse-encapsulate", "jdk-ml-kem-768-parse-encapsulate"},
            new String[] {"ml-dsa-65-verify", "jdk-ml-dsa-65-verify"},
            new String[] {"ml-dsa-65-pubkey-parse", "jdk-ml-dsa-65-pubkey-parse"},
            new String[] {"ml-dsa-65-parse-verify", "jdk-ml-dsa-65-parse-verify"});

    private ArmDiff() {
    }

    public static void main(String[] args) throws IOException {
        long seed = 20260717;
        long inputs = 100_000;
        long timeoutMillis = 5_000;
        Path out = Path.of("results", "arm-diff");
        String label = "";
        for (String arg : args) {
            if (arg.startsWith("--seed=")) {
                seed = Long.parseLong(arg.substring("--seed=".length()));
            } else if (arg.startsWith("--inputs=")) {
                inputs = Long.parseLong(arg.substring("--inputs=".length()));
            } else if (arg.startsWith("--timeout-ms=")) {
                timeoutMillis = Long.parseLong(arg.substring("--timeout-ms=".length()));
            } else if (arg.startsWith("--out=")) {
                out = Path.of(arg.substring("--out=".length()));
            } else if (arg.startsWith("--label=")) {
                label = arg.substring("--label=".length());
            } else {
                throw new IllegalArgumentException("unknown option: " + arg);
            }
        }

        StringBuilder md = new StringBuilder();
        md.append("# Per-input comparison of the two arms (design amendment A7)\n\n");
        md.append("Generated ").append(Instant.now()).append(" by `org.pqcfuzz.run.ArmDiff`.\n\n");
        md.append("| Setting | Value |\n|---|---|\n");
        md.append("| Label | ").append(label.isEmpty() ? "(none)" : label).append(" |\n");
        md.append("| JVM | ").append(System.getProperty("java.vm.name")).append(' ')
                .append(System.getProperty("java.vm.version")).append(" |\n");
        md.append("| Campaign seed | `").append(seed).append("` |\n");
        md.append("| Inputs per pair | ").append(String.format("%,d", inputs)).append(" |\n");
        md.append("| Per-input timeout | ").append(timeoutMillis).append(" ms |\n\n");
        md.append("For every input the mutation stream is the one the campaign used under this seed, and the ")
                .append("two outcomes are the campaign's own classifier applied to each arm. A cell `X / Y` counts ")
                .append("inputs that Bouncy Castle scored `X` and the JDK scored `Y`.\n\n");

        long totalInputs = 0;
        long totalDisagreements = 0;
        for (String[] pair : PAIRS) {
            FuzzTarget bc = Targets.create(pair[0], seed);
            FuzzTarget jdk = Targets.create(pair[1], seed);
            boolean sameCorpus = bc.nominalInputLength() == jdk.nominalInputLength()
                    && bc.seedCorpus().size() == jdk.seedCorpus().size();
            if (sameCorpus) {
                for (int i = 0; i < bc.seedCorpus().size(); i++) {
                    if (!Arrays.equals(bc.seedCorpus().get(i), jdk.seedCorpus().get(i))) {
                        sameCorpus = false;
                        break;
                    }
                }
            }
            md.append("## `").append(pair[0]).append("` against `").append(pair[1]).append("`\n\n");
            md.append("Seed corpora byte-identical: ").append(sameCorpus ? "yes" : "NO").append("; nominal length ")
                    .append(bc.nominalInputLength()).append(" bytes; ").append(bc.seedCorpus().size())
                    .append(" seed inputs.\n\n");
            if (!sameCorpus) {
                md.append("Skipped: the pair does not share its inputs.\n\n");
                continue;
            }

            Map<String, Long> cells = new TreeMap<>();
            Map<String, Long> cellsWrongLength = new TreeMap<>();
            long disagreements = 0;
            long disagreementsWrongLength = 0;
            List<String> firstDisagreements = new ArrayList<>();
            Mutator mutator = new Mutator(
                    bc.seedCorpus(),
                    bc.nominalInputLength(),
                    RandomGeneratorFactory.of("L64X128MixRandom").create(seed));
            try (TargetExecutor bcExecutor = new TargetExecutor(bc, timeoutMillis);
                 TargetExecutor jdkExecutor = new TargetExecutor(jdk, timeoutMillis)) {
                for (long i = 0; i < inputs; i++) {
                    MutatedInput input = mutator.next();
                    Outcome a = bcExecutor.execute(input.bytes()).outcome();
                    Outcome b = jdkExecutor.execute(input.bytes()).outcome();
                    boolean wrongLength = input.bytes().length != bc.nominalInputLength();
                    String cell = a + " / " + b;
                    cells.merge(cell, 1L, Long::sum);
                    if (wrongLength) {
                        cellsWrongLength.merge(cell, 1L, Long::sum);
                    }
                    if (a != b) {
                        disagreements++;
                        if (wrongLength) {
                            disagreementsWrongLength++;
                        }
                        if (firstDisagreements.size() < 5) {
                            firstDisagreements.add(String.format("input %,d (%s, %d bytes): %s", i + 1,
                                    input.mutation(), input.bytes().length, cell));
                        }
                    }
                }
            }
            totalInputs += inputs;
            totalDisagreements += disagreements;

            md.append("| Bouncy Castle / JDK | Inputs | Of which wrong-length |\n|---|---:|---:|\n");
            for (Map.Entry<String, Long> e : cells.entrySet()) {
                md.append("| `").append(e.getKey()).append("` | ").append(String.format("%,d", e.getValue()))
                        .append(" | ").append(String.format("%,d", cellsWrongLength.getOrDefault(e.getKey(), 0L)))
                        .append(" |\n");
            }
            md.append("\n**Disagreements: ").append(String.format("%,d", disagreements)).append(" of ")
                    .append(String.format("%,d", inputs)).append("** (")
                    .append(String.format("%,d", disagreementsWrongLength)).append(" on wrong-length inputs, ")
                    .append(String.format("%,d", disagreements - disagreementsWrongLength))
                    .append(" on correct-length inputs).\n\n");
            if (!firstDisagreements.isEmpty()) {
                md.append("First disagreements: ").append(String.join("; ", firstDisagreements)).append(".\n\n");
            }
            System.out.printf("%s vs %s: %,d disagreements of %,d%n", pair[0], pair[1], disagreements, inputs);
        }
        md.append("## Total\n\n").append(String.format("%,d", totalDisagreements)).append(" disagreements over ")
                .append(String.format("%,d", totalInputs)).append(" shared inputs.\n");

        Files.createDirectories(out);
        Path report = out.resolve("ARM-DIFF.md");
        Files.writeString(report, md.toString(), StandardCharsets.UTF_8);
        System.out.println("Report written to " + report);
    }
}
